In [169]:
import pandas as pd
import numpy as np
from scipy.stats.stats import pearsonr

In [170]:
'''This function reads 2013_-_2014_School_Quality_Reports_Results_for_High_Schools.csv and 
returns a dataframe with the names of the high schools and various ways in which to measure its quality. '''

def getSchoolQualityData():
    quality = pd.read_csv("2013_-_2014_School_Quality_Reports_Results_for_High_Schools.csv", usecols = [1, 18, 19, 26, 27, 28, 35])
    quality['School Name'] = quality['School Name'].str.upper()  #Match the values in this column to the values in the Public_Schools.csv data
    quality = quality.rename(columns = {'Quality Review: How interesting and challenging is the curriculum?':'Curriculum', 
                                        'Quality Review: How effective is the teaching and learning?':'Learning',
                                        'Quality Review: How well does the school assess what students are learning?': 'Assessment', 
                                       }) 
    #To make the Quality Reviews numerical values
    for col in quality.columns[3:6]:
        for i in range(0, len(quality)):
            if quality[col][i] == 'Proficient':
                quality[col][i] = 3
            elif quality[col][i] == 'Well Developed':
                quality[col][i] = 2
            elif quality[col][i] == 'Developing':
                quality[col][i] = 1
    return quality
getSchoolQualityData()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,School Name,Average Grade 8 English Proficiency,Average Grade 8 Math Proficiency,Curriculum,Learning,Assessment,Average SAT Score
0,HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES,2.17,2.07,3,1,3,1131.0
1,UNIVERSITY NEIGHBORHOOD HIGH SCHOOL,2.23,2.26,3,3,3,1176.0
2,EAST SIDE COMMUNITY SCHOOL,2.66,2.58,NaN,NaN,NaN,1311.0
3,MARTA VALLE HIGH SCHOOL,2.34,2.15,1,1,1,1150.0
4,"NEW EXPLORATIONS INTO SCIENCE, TECHNOLOGY AND ...",3.48,3.49,2,3,3,1773.0
5,BARD HIGH SCHOOL EARLY COLLEGE,3.70,3.64,2,2,3,1963.0
6,47 THE AMERICAN SIGN LANGUAGE AND ENGLISH SECO...,2.30,2.17,3,3,3,1212.0
7,THE URBAN ASSEMBLY SCHOOL FOR EMERGENCY MANAGE...,2.39,2.23,NaN,NaN,NaN,NaN
8,STEPHEN T. MATHER BUILDING ARTS & CRAFTSMANSHI...,2.34,2.20,NaN,NaN,NaN,NaN
9,FOOD AND FINANCE HIGH SCHOOL,2.48,2.32,NaN,NaN,NaN,1146.0
10,ESSEX STREET ACADEMY,2.47,2.25,2,3,2,1199.0
11,HIGH SCHOOL OF HOSPITALITY MANAGEMENT,2.32,2.26,NaN,NaN,NaN,1182.0
12,PACE HIGH SCHOOL,2.64,2.51,NaN,NaN,NaN,1368.0
13,URBAN ASSEMBLY SCHOOL OF DESIGN AND CONSTRUCTI...,2.33,2.26,3,3,3,1304.0
14,"FACING HISTORY SCHOOL, THE",2.19,2.13,3,3,3,1090.0
15,"URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW, THE",2.37,2.23,3,3,3,1191.0
16,LOWER MANHATTAN ARTS ACADEMY,2.40,2.20,NaN,NaN,NaN,1236.0
17,URBAN ASSEMBLY SCHOOL OF BUSINESS FOR YOUNG WO...,2.34,2.20,3,3,1,1282.0
18,GRAMERCY ARTS HIGH SCHOOL,2.55,2.27,1,1,1,1263.0
19,NYC ISCHOOL,3.11,2.81,2,3,2,1529.0
20,MANHATTAN BUSINESS ACADEMY,2.34,2.29,2,3,3,1245.0
21,BUSINESS OF SPORTS SCHOOL,2.26,2.17,3,3,1,1145.0
22,THE HIGH SCHOOL FOR LANGUAGE AND DIPLOMACY,2.44,2.37,3,3,3,1164.0
23,HIGH SCHOOL FOR ENVIRONMENTAL STUDIES,2.62,2.60,3,3,3,1444.0
24,INSTITUTE FOR COLLABORATIVE EDUCATION,2.84,2.40,2,2,2,1548.0
25,PROFESSIONAL PERFORMING ARTS HIGH SCHOOL,3.15,2.77,3,3,3,1553.0
26,BARUCH COLLEGE CAMPUS HIGH SCHOOL,3.23,3.24,NaN,NaN,NaN,1617.0
27,N.Y.C. LAB SCHOOL FOR COLLABORATIVE STUDIES,3.29,3.15,NaN,NaN,NaN,1712.0
28,SCHOOL OF THE FUTURE HIGH SCHOOL,3.03,2.72,2,2,2,1550.0
29,N.Y.C. MUSEUM SCHOOL,3.18,3.11,NaN,NaN,NaN,1495.0
...,...,...,...,...,...,...,...
454,NEW VISIONS CHARTER HIGH SCHOOL FOR ADVANCED M...,2.42,2.26,NaN,NaN,NaN,NaN
455,NEW VISIONS CHARTER HIGH SCHOOL FOR THE HUMANI...,2.31,2.15,NaN,NaN,NaN,NaN
456,CONEY ISLAND PREPARATORY PUBLIC CHARTER SCHOOL,2.85,2.84,NaN,NaN,NaN,NaN
457,ACHIEVEMENT FIRST HS,NaN,NaN,NaN,NaN,NaN,1421.0
458,UNCOMMON CHARTER HS 2,NaN,NaN,NaN,NaN,NaN,NaN
459,ACHIEVEMENT FIRST UNIVERSITY PREP,NaN,NaN,NaN,NaN,NaN,NaN
460,UNCOMMON CHARTER HS,NaN,NaN,NaN,NaN,NaN,NaN
461,THE OPPORTUNITY CHARTER SCHOOL,2.03,1.97,NaN,NaN,NaN,1069.0
462,HARLEM CHILDREN'S ZONE PROMISE ACADEMY 1 CHART...,2.57,2.56,NaN,NaN,NaN,NaN
463,HARLEM CHILDREN'S ZONE PROMISE ACADEMY II CHAR...,2.54,2.43,NaN,NaN,NaN,NaN
464,DEMOCRACY PREP CHARTER SCHOOL,2.62,2.67,NaN,NaN,NaN,1515.0
465,NEW HEIGHTS ACADEMY CHARTER SCHOOL,2.29,2.39,NaN,NaN,NaN,NaN
466,RENAISSANCE CHARTER HIGH SCHOOL FOR INNOVATION,2.17,2.01,NaN,NaN,NaN,1079.0
467,DEMOCRACY PREP HARLEM CHARTER SCHOOL,2.79,2.70,NaN,NaN,NaN,NaN
468,BROOME STREET ACADEMY CHARTER SCHOOL,2.23,2.03,NaN,NaN,NaN,NaN
469,HARLEM VILLAGE ACADEMY HS,NaN,NaN,NaN,NaN,NaN,1488.0
470,KIPP NYC COLLEGE PREP,NaN,NaN,NaN,NaN,NaN,1356.0
471,RENAISSANCE CHARTER SCHOOL,2.60,2.54,NaN,NaN,NaN,1360.0
472,JOHN W. LAVELLE PREPARATORY CHARTER SCHOOL,2.50,2.33,NaN,NaN,NaN,NaN
473,BRONX LIGHTHOUSE CHARTER SCHOOL,2.52,2.36,NaN,NaN,NaN,NaN
474,NEW VISIONS CHARTER HIGH SCHOOL FOR ADVANCED M...,2.28,2.26,NaN,NaN,NaN,NaN
475,NEW VISIONS CHARTER HIGH SCHOOL FOR THE HUMANI...,2.17,2.05,NaN,NaN,NaN,NaN
476,HYDE LEADERSHIP CHARTER SCHOOL,2.41,2.25,NaN,NaN,NaN,1205.0
477,INTERNATIONAL LEADERSHIP CHARTER HIGH SCHOOL,2.48,2.39,NaN,NaN,NaN,1285.0
478,UNIVERSITY PREP CHARTER HIGH SCHOOL,2.45,2.42,NaN,NaN,NaN,1281.0
479,"NYC CHARTER HIGH SCHOOL FOR ARCHITECTURE, ENGI...",2.26,2.21,NaN,NaN,NaN,1088.0
480,DR. RICHARD IZQUIERDO HEALTH AND SCIENCE CHART...,2.23,2.10,NaN,NaN,NaN,NaN
481,NEW VISIONS CHARTER HIGH SCHOOL FOR ADVANCED M...,2.43,2.35,NaN,NaN,NaN,NaN
482,NEW VISIONS CHARTER HIGH SCHOOL FOR THE HUMANI...,2.25,2.09,NaN,NaN,NaN,NaN
483,BRONX PREPARATORY CHARTER SCHOOL,2.48,2.44,NaN,NaN,NaN,1271.0

In [171]:
'''This function reads Public_Schools.csv and merges it with the school quality data to return
a dataframe with the locations of each school and their quality'''
def getSchoolData(): 
    schools = pd.read_csv("Public_Schools.csv", usecols = [3, 4, 5, 6, 7, 8])#, index_col = 'NAME')
    quality = getSchoolQualityData()
    data = pd.merge(schools, quality, how = 'inner', left_on = 'NAME', right_on = 'School Name')
    data = data.drop(['School Name'], axis = 1)
    return data
getSchoolData()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,Average Grade 8 English Proficiency,Average Grade 8 Math Proficiency,Curriculum,Learning,Assessment,Average SAT Score
0,360012302863,RICHMOND HILL HIGH SCHOOL,89-30 114TH ST,RICHMOND HILL,NY,11418,2.32,2.21,1,3,1,1186.0
1,130057001873,RICHMOND HILL HIGH SCHOOL,1 WILDCAT DR,RICHMOND HILL,GA,31324,2.32,2.21,1,3,1,1186.0
2,360004204466,BRONX PREPARATORY CHARTER SCHOOL,3872 3RD AVE,BRONX,NY,10457,2.48,2.44,NaN,NaN,NaN,1271.0
3,120156004035,BAYSIDE HIGH SCHOOL,14405 49TH ST N,CLEARWATER,FL,33762,2.83,2.77,NaN,NaN,NaN,1511.0
4,120015003293,BAYSIDE HIGH SCHOOL,1901 DEGROODT RD SW,PALM BAY,FL,32908,2.83,2.77,NaN,NaN,NaN,1511.0
5,360009901917,BAYSIDE HIGH SCHOOL,32-24 CORP KENNEDY ST,BAYSIDE,NY,11361,2.83,2.77,NaN,NaN,NaN,1511.0
6,360008401338,HEALTH OPPORTUNITIES HIGH SCHOOL,350 GERARD AVE,BRONX,NY,10451,2.18,2.14,3,1,3,1127.0
7,360007605621,BARD HIGH SCHOOL EARLY COLLEGE,525 E HOUSTON ST,NEW YORK,NY,10002,3.70,3.64,2,2,3,1963.0
8,240009001735,BARD HIGH SCHOOL EARLY COLLEGE,1101 N. WOLFE STREET,BALTIMORE,MD,21212,3.70,3.64,2,2,3,1963.0
9,360008100590,CHOIR ACADEMY OF HARLEM,2005 MADISON AVE,NEW YORK,NY,10035,2.22,2.04,3,3,3,NaN
10,360007700582,LANDMARK HIGH SCHOOL,351 W 18TH ST,NEW YORK,NY,10011,2.19,2.10,3,1,3,1211.0
11,360010302850,PORT RICHMOND HIGH SCHOOL,85 ST JOSEPHS AVE,STATEN ISLAND,NY,10302,2.35,2.16,3,3,3,1302.0
12,341812003670,JOHN F. KENNEDY HIGH SCHOOL,200 WASHINGTON AVENUE,ISELIN,NJ,8830,2.15,2.08,NaN,NaN,NaN,1060.0
13,660000200076,JOHN F. KENNEDY HIGH SCHOOL,331 N. MARINE DRIVE,TAMUNING,GU,96930,2.15,2.08,NaN,NaN,NaN,1060.0
14,263354006899,JOHN F. KENNEDY HIGH SCHOOL,13505 J F KENNEDY DR,TAYLOR,MI,48180,2.15,2.08,NaN,NaN,NaN,1060.0
15,90483000979,JOHN F. KENNEDY HIGH SCHOOL,422 HIGHLAND AVE.,WATERBURY,CT,6708,2.15,2.08,NaN,NaN,NaN,1060.0
16,360008706397,BRONX COLLABORATIVE HIGH SCHOOL,100 W MOSHOLU PKWY S,BRONX,NY,10468,2.34,2.25,NaN,NaN,NaN,NaN
17,360009205930,KHALIL GIBRAN INTERNATIONAL ACADEMY,326 SCHERMERHORN ST,BROOKLYN,NY,11217,2.21,2.02,NaN,NaN,NaN,NaN
18,360011905703,WILLIAMSBURG HIGH SCHOOL FOR ARCHITECTURE AND ...,257 N 6TH ST,BROOKLYN,NY,11211,2.35,2.26,NaN,NaN,NaN,1249.0
19,360015201906,ABRAHAM LINCOLN HIGH SCHOOL,2800 OCEAN PKWY,BROOKLYN,NY,11235,2.45,2.36,3,1,3,1269.0
20,190822000409,ABRAHAM LINCOLN HIGH SCHOOL,1205 BONHAM AVE,COUNCIL BLUFFS,IA,51503,2.45,2.36,3,1,3,1269.0
21,80336000305,ABRAHAM LINCOLN HIGH SCHOOL,2285 SOUTH FEDERAL BOULEVARD,DENVER,CO,80219,2.45,2.36,3,1,3,1269.0
22,130255004212,DISCOVERY HIGH SCHOOL,1335 OLD NORCROSS RD,LAWRENCEVILLE,GA,30046,2.19,2.09,3,3,2,1227.0
23,360008705557,DISCOVERY HIGH SCHOOL,2780 RESERVOIR AVE,BRONX,NY,10468,2.19,2.09,3,3,2,1227.0
24,370336002754,DISCOVERY HIGH SCHOOL,301 WEST 18TH ST,NEWTON,NC,28658,2.19,2.09,3,3,2,1227.0
25,80648000051,DISCOVERY HIGH SCHOOL,701 WIDEFIELD DRIVE,COLORADO SPRINGS,CO,80911,2.19,2.09,3,3,2,1227.0
26,530447003454,DISCOVERY HIGH SCHOOL,2742 HARDING BLVD,LONGVIEW,WA,98632,2.19,2.09,3,3,2,1227.0
27,360009804895,MIDDLE COLLEGE HIGH SCHOOL AT LAGUARDIA COMMUN...,45-35 VAN DAM ST,LONG ISLAND CITY,NY,11101,2.34,2.35,3,3,3,1145.0
28,360007706191,INTERNATIONAL HIGH SCHOOL AT UNION SQUARE,40 IRVING PL,NEW YORK,NY,10003,1.75,2.24,3,3,3,1041.0
29,360008706247,CROTONA INTERNATIONAL HIGH SCHOOL,2474 CROTONA AVE,BRONX,NY,10458,1.70,1.92,3,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
301,360007705500,MANHATTAN BRIDGES HIGH SCHOOL,525 W 50TH ST,NEW YORK,NY,10019,2.03,2.26,NaN,NaN,NaN,1089.0
302,360007705532,HIGH SCHOOL FOR DUAL LANGUAGE AND ASIAN STUDIES,350 GRAND ST,NEW YORK,NY,10002,2.59,3.35,NaN,NaN,NaN,1532.0
303,360007701297,TALENT UNLIMITED HIGH SCHOOL,317 E 67TH ST,NEW YORK,NY,10021,3.00,2.68,2,3,2,1434.0
304,360007706309,UNION SQUARE ACADEMY FOR HEALTH SCIENCES,40 IRVING PL,NEW YORK,NY,10003,2.46,2.37,NaN,NaN,NaN,NaN
305,360007603680,UNIVERSITY NEIGHBORHOOD HIGH SCHOOL,200 MONROE ST,NEW YORK,NY,10002,2.23,2.26,3,3,3,1176.0
306,360010206070,ACADEMY FOR CAREERS IN TELEVISION AND FILM,1-50 51ST AVE,LONG ISLAND CITY,NY,11101,2.64,2.36,2,2,2,1276.0
307,360007601275,MARTA VALLE HIGH SCHOOL,145 STANTON ST,NEW YORK,NY,10002,2.34,2.15,1,1,1,1150.0
308,360008105944,COLUMBIA SECONDARY SCHOOL,425 W 123RD ST,NEW YORK,NY,10027,3.39,3.05,3,3,2,NaN
309,360009605967,VICTORY COLLEGIATE HIGH SCHOOL,6565 FLATLANDS AVE,BROOKLYN,NY,11236,2.30,2.11,3,3,2,1089.0
310,360010205511,INFORMATION TECHNOLOGY HIGH SCHOOL,21-16 44TH RD,LONG ISLAND CITY,NY,11101,2.44,2.43,3,1,1,1304.0
311,360008600795,BRONX LEADERSHIP ACADEMY HIGH SCHOOL,1710 WEBSTER AVE,BRONX,NY,10457,2.19,2.12,3,3,3,1173.0
312,360007704519,HIGH SCHOOL OF GRAPHIC COMMUNICATION ARTS,439 W 49TH ST,NEW YORK,NY,10019,2.31,2.12,Underdeveloped,Underdeveloped,1,1197.0
313,360012006046,ACADEMY OF INNOVATIVE TECHNOLOGY,999 JAMAICA AVE,BROOKLYN,NY,11208,2.22,2.10,3,3,3,1139.0
314,360007700595,UNITY CENTER FOR URBAN TECHNOLOGIES,111 E 33RD ST,NEW YORK,NY,10016,2.25,2.12,1,1,3,1051.0
315,360008805683,BRONX LAB SCHOOL,800 E GUN HILL RD,BRONX,NY,10467,2.30,2.17,3,1,3,1174.0
316,360012202014,JOHN BOWNE HIGH SCHOOL,63-25 MAIN ST,FLUSHING,NY,11367,2.45,2.42,3,3,3,1294.0
317,360009005805,MOTT HALL V,1551 E 172ND ST,BRONX,NY,10472,2.40,2.45,NaN,NaN,NaN,NaN
318,360009405518,FREDERICK DOUGLASS ACADEMY IV SECONDARY SCHOOL,1014 LAFAYETTE AVE,BROOKLYN,NY,11221,2.19,2.02,3,3,3,NaN
319,360007701723,PROFESSIONAL PERFORMING ARTS HIGH SCHOOL,328 W 48TH ST,NEW YORK,NY,10036,3.15,2.77,3,3,3,1553.0
320,360008705796,THEATRE ARTS PRODUCTION COMPANY SCHOOL,2225 WEBSTER AVE,BRONX,NY,10457,2.45,2.23,3,1,3,1213.0
321,360008505660,GATEWAY SCHOOL FOR ENVIRONMENTAL RESEARCH AND ...,1980 LAFAYETTE AVE,BRONX,NY,10473,2.12,1.98,3,3,3,1094.0
322,360008705674,WEST BRONX ACADEMY FOR THE FUTURE,500 E FORDHAM RD,BRONX,NY,10458,2.20,2.11,1,1,1,1172.0
323,360008805179,BRONX HIGH SCHOOL FOR THE VISUAL ARTS,2040 ANTIN PL,BRONX,NY,10462,2.37,2.11,1,1,1,1270.0
324,360015302873,SHEEPSHEAD BAY HIGH SCHOOL,3000 AVE X,BROOKLYN,NY,11235,2.26,2.17,1,1,1,1158.0
325,360008305784,CITY COLLEGE ACADEMY OF THE ARTS,4600 BROADWAY,NEW YORK,NY,10040,2.80,2.87,NaN,NaN,NaN,1360.0
326,360007701911,ART AND DESIGN HIGH SCHOOL,231-249 E 56TH ST,NEW YORK,NY,10019,2.78,2.53,3,3,3,1365.0
327,360015302032,MIDWOOD HIGH SCHOOL,2839 BEDFORD AVE,BROOKLYN,NY,11210,3.06,3.05,3,3,3,1561.0
328,360007701720,INSTITUTE FOR COLLABORATIVE EDUCATION,345 E 15TH ST,NEW YORK,NY,10003,2.84,2.40,2,2,2,1548.0
329,360008506357,BRONX COMPASS HIGH SCHOOL,1980 LAFAYETTE AVE,BRONX,NY,10473,2.29,2.10,NaN,NaN,NaN,NaN
330,360094806058,NORTHSIDE CHARTER HIGH SCHOOL,424 LEONARD ST-4TH FL,BROOKLYN,NY,11222,2.35,2.24,NaN,NaN,NaN,1184.0

In [172]:
'''This function merges the housing prices data with the high school data to return
a dataframe with the quality of schools and the housing prices in a region'''
def getFinalData():
    schools = getSchoolData()
    housing = pd.read_csv("Zip_Zhvi_AllHomes.csv")
    housing2 = pd.DataFrame()
    housing2['RegionName'] = housing['RegionName']
    #Use only 2014 housing price data. 
    for col in housing.columns:
        if '2014' in str(col):
            housing2[col] = housing[col]
    #Calculate the mean housing price in 2014, across all 12 months. 
    housing2['Average 2014 Prices'] = housing2.mean(axis = 1)
    housing2 = housing2[['RegionName', 'Average 2014 Prices']]
    data = pd.merge(schools, housing2, how = 'inner', left_on = 'ZIP', right_on = 'RegionName')
    data = data.drop(['RegionName'], axis=1)
    data = data.drop_duplicates(subset = 'ADDRESS') #Drop duplicate entries of the same schools. 
    return data
getFinalData()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,Average Grade 8 English Proficiency,Average Grade 8 Math Proficiency,Curriculum,Learning,Assessment,Average SAT Score,Average 2014 Prices
0,360012302863,RICHMOND HILL HIGH SCHOOL,89-30 114TH ST,RICHMOND HILL,NY,11418,2.32,2.21,1,3,1,1186.0,3.850120e+05
1,130057001873,RICHMOND HILL HIGH SCHOOL,1 WILDCAT DR,RICHMOND HILL,GA,31324,2.32,2.21,1,3,1,1186.0,2.048224e+05
2,360004204466,BRONX PREPARATORY CHARTER SCHOOL,3872 3RD AVE,BRONX,NY,10457,2.48,2.44,NaN,NaN,NaN,1271.0,1.437893e+05
3,360008605670,EAGLE ACADEMY FOR YOUNG MEN,4143 3RD AVE,BRONX,NY,10457,2.25,2.21,3,3,3,1189.0,1.437893e+05
4,360008605882,DREAMYARD PREPARATORY SCHOOL,240 E 172ND ST,BRONX,NY,10457,2.20,2.04,3,1,3,1091.0,1.437893e+05
7,360008605793,MOTT HALL BRONX HIGH SCHOOL,1595 BATHGATE AVE,BRONX,NY,10457,2.26,2.24,3,1,3,1093.0,1.437893e+05
8,360008605795,LEADERSHIP INSTITUTE,1701 FULTON AVE,BRONX,NY,10457,2.03,1.93,3,3,3,1013.0,1.437893e+05
9,360008600795,BRONX LEADERSHIP ACADEMY HIGH SCHOOL,1710 WEBSTER AVE,BRONX,NY,10457,2.19,2.12,3,3,3,1173.0,1.437893e+05
10,360008705796,THEATRE ARTS PRODUCTION COMPANY SCHOOL,2225 WEBSTER AVE,BRONX,NY,10457,2.45,2.23,3,1,3,1213.0,1.437893e+05
11,120156004035,BAYSIDE HIGH SCHOOL,14405 49TH ST N,CLEARWATER,FL,33762,2.83,2.77,NaN,NaN,NaN,1511.0,1.675890e+05
12,120015003293,BAYSIDE HIGH SCHOOL,1901 DEGROODT RD SW,PALM BAY,FL,32908,2.83,2.77,NaN,NaN,NaN,1511.0,1.116672e+05
13,360009901917,BAYSIDE HIGH SCHOOL,32-24 CORP KENNEDY ST,BAYSIDE,NY,11361,2.83,2.77,NaN,NaN,NaN,1511.0,5.663194e+05
14,360007605621,BARD HIGH SCHOOL EARLY COLLEGE,525 E HOUSTON ST,NEW YORK,NY,10002,3.70,3.64,2,2,3,1963.0,8.555895e+05
15,360007705625,PACE HIGH SCHOOL,100 HESTER ST,NEW YORK,NY,10002,2.64,2.51,NaN,NaN,NaN,1368.0,8.555895e+05
16,360007605614,HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES,220 HENRY ST,NEW YORK,NY,10002,2.17,2.07,3,1,3,1131.0,8.555895e+05
17,360007705499,NEW DESIGN HIGH SCHOOL,350 GRAND ST,NEW YORK,NY,10002,2.36,2.17,NaN,NaN,NaN,1160.0,8.555895e+05
21,360007603680,UNIVERSITY NEIGHBORHOOD HIGH SCHOOL,200 MONROE ST,NEW YORK,NY,10002,2.23,2.26,3,3,3,1176.0,8.555895e+05
22,360007601275,MARTA VALLE HIGH SCHOOL,145 STANTON ST,NEW YORK,NY,10002,2.34,2.15,1,1,1,1150.0,8.555895e+05
23,240009001735,BARD HIGH SCHOOL EARLY COLLEGE,1101 N. WOLFE STREET,BALTIMORE,MD,21212,3.70,3.64,2,2,3,1963.0,2.162325e+05
24,360008100590,CHOIR ACADEMY OF HARLEM,2005 MADISON AVE,NEW YORK,NY,10035,2.22,2.04,3,3,3,NaN,5.238624e+05
25,360014005777,HARLEM CHILDREN'S ZONE PROMISE ACADEMY II CHAR...,35 E 125TH ST,NEW YORK,NY,10035,2.54,2.43,NaN,NaN,NaN,NaN,5.238624e+05
26,360007900579,COALITION SCHOOL FOR SOCIAL CHANGE,2351 1ST AVE,NEW YORK,NY,10035,2.15,2.03,3,1,1,1092.0,5.238624e+05
27,360007700582,LANDMARK HIGH SCHOOL,351 W 18TH ST,NEW YORK,NY,10011,2.19,2.10,3,1,3,1211.0,9.656582e+05
29,360007706361,HARVEST COLLEGIATE HIGH SCHOOL,34 W 14TH ST,NEW YORK,NY,10011,2.67,2.37,NaN,NaN,NaN,NaN,9.656582e+05
33,360010302850,PORT RICHMOND HIGH SCHOOL,85 ST JOSEPHS AVE,STATEN ISLAND,NY,10302,2.35,2.16,3,3,3,1302.0,3.063448e+05
34,341812003670,JOHN F. KENNEDY HIGH SCHOOL,200 WASHINGTON AVENUE,ISELIN,NJ,8830,2.15,2.08,NaN,NaN,NaN,1060.0,2.533318e+05
35,263354006899,JOHN F. KENNEDY HIGH SCHOOL,13505 J F KENNEDY DR,TAYLOR,MI,48180,2.15,2.08,NaN,NaN,NaN,1060.0,6.832300e+04
36,90483000979,JOHN F. KENNEDY HIGH SCHOOL,422 HIGHLAND AVE.,WATERBURY,CT,6708,2.15,2.08,NaN,NaN,NaN,1060.0,1.122079e+05
37,360008706397,BRONX COLLABORATIVE HIGH SCHOOL,100 W MOSHOLU PKWY S,BRONX,NY,10468,2.34,2.25,NaN,NaN,NaN,NaN,1.523319e+05
38,360008705557,DISCOVERY HIGH SCHOOL,2780 RESERVOIR AVE,BRONX,NY,10468,2.19,2.09,3,3,2,1227.0,1.523319e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,360007806185,FRANK MCCOURT HIGH SCHOOL,145 W 84TH ST,NEW YORK,NY,10024,2.87,2.61,3,3,1,1468.0,1.014374e+06
289,360007702034,MURRY BERGTRAUM HIGH SCHOOL FOR BUSINESS CAREERS,411 PEARL ST,NEW YORK,NY,10038,2.35,2.23,1,1,1,1206.0,1.175092e+06
290,360009206111,SUNSET PARK HIGH SCHOOL,153 35TH ST,BROOKLYN,NY,11232,2.27,2.16,3,2,2,1130.0,4.030547e+05
291,360010106220,CAMBRIA HEIGHTS ACADEMY,188-04 91ST AVE,HOLLIS,NY,11423,2.36,2.14,3,3,3,1200.0,3.977635e+05
292,360008805803,NEW WORLD HIGH SCHOOL,921 E 228TH ST,BRONX,NY,10466,1.92,2.06,NaN,NaN,NaN,1100.0,3.163817e+05
293,360008305909,WASHINGTON HEIGHTS EXPEDITIONARY LEARNING SCHOOL,511 W 182ND ST,NEW YORK,NY,10033,2.40,2.50,3,2,2,1286.0,4.078408e+05
294,360008305878,COMMUNITY HEALTH ACADEMY OF THE HEIGHTS,504 W 158TH ST,NEW YORK,NY,10033,2.16,2.08,3,1,3,1135.0,4.078408e+05
295,120126001277,VANGUARD HIGH SCHOOL,7 NW 28TH ST,OCALA,FL,34475,2.38,2.22,3,3,3,1248.0,6.065854e+04
296,360009505885,ACADEMY OF HOSPITALITY AND TOURISM,911 FLATBUSH AVE,BROOKLYN,NY,11226,2.23,2.02,3,1,1,1095.0,4.438082e+05
297,261455005145,FLUSHING HIGH SCHOOL,5039 DELAND RD,FLUSHING,MI,48433,2.37,2.30,1,1,1,1260.0,1.119076e+05
298,360009902030,MARTIN VAN BUREN HIGH SCHOOL,230-17 HILLSIDE AVE,QUEENS VILLAGE,NY,11427,2.33,2.15,1,1,1,1253.0,4.120510e+05
299,360010202887,WILLIAM CULLEN BRYANT HIGH SCHOOL,48-10 31ST AVE,LONG ISLAND CITY,NY,11103,2.44,2.44,1,1,1,1331.0,4.695916e+05
300,360099806114,SUMMIT ACADEMY CHARTER SCHOOL,27 HUNTINGTON ST,BROOKLYN,NY,11231,2.36,2.47,NaN,NaN,NaN,NaN,1.054286e+06
301,360009205497,BROOKLYN SECONDARY SCHOOL FOR COLLABORATIVE ST...,610 HENRY ST,BROOKLYN,NY,11231,2.50,2.20,2,2,2,1257.0,1.054286e+06
302,360007805627,FREDERICK DOUGLASS ACADEMY II SECONDARY SCHOOL,215 W 114TH ST,NEW YORK,NY,10026,2.15,2.01,2,3,1,1114.0,7.105108e+05
303,360016705891,NEW HEIGHTS ACADEMY CHARTER SCHOOL,1818 AMSTERDAM AVE,NEW YORK,NY,10031,2.29,2.39,NaN,NaN,NaN,NaN,5.032502e+05
304,360007600695,EAST SIDE COMMUNITY SCHOOL,420 E 12TH ST,NEW YORK,NY,10009,2.66,2.58,NaN,NaN,NaN,1311.0,6.305265e+05
305,172035002292,JAMAICA HIGH SCHOOL,7087 N 600 EAST RD,SIDELL,IL,61876,2.11,2.15,NaN,NaN,NaN,1034.0,5.193577e+04
306,80258006465,FOUNDATIONS ACADEMY,340 SOUTH 45TH AVENUE,BRIGHTON,CO,80601,2.11,2.02,1,1,Underdeveloped,NaN,2.232632e+05
307,360009901953,FRANCIS LEWIS HIGH SCHOOL,58-20 UTOPIA PKY,FRESH MEADOWS,NY,11365,2.87,2.96,3,3,3,1538.0,4.925072e+05
308,360010001951,FOREST HILLS HIGH SCHOOL,67-01 110TH ST,FOREST HILLS,NY,11375,2.87,2.80,NaN,NaN,NaN,1509.0,2.798926e+05
309,360007702877,STUYVESANT HIGH SCHOOL,345 CHAMBERS ST,NEW YORK,NY,10282,3.99,4.14,NaN,NaN,NaN,2133.0,2.211596e+06
310,360012204485,TOWNSEND HARRIS HIGH SCHOOL,149-11 MELBOURNE AVE,FLUSHING,NY,11367,3.99,4.05,NaN,NaN,NaN,1955.0,2.468686e+05
311,360012202014,JOHN BOWNE HIGH SCHOOL,63-25 MAIN ST,FLUSHING,NY,11367,2.45,2.42,3,3,3,1294.0,2.468686e+05
312,360010005935,YORK EARLY COLLEGE ACADEMY,108-35 167TH ST,JAMAICA,NY,11433,2.92,2.76,2,3,3,1358.0,3.180109e+05
313,360008105944,COLUMBIA SECONDARY SCHOOL,425 W 123RD ST,NEW YORK,NY,10027,3.39,3.05,3,3,2,NaN,4.626464e+05
314,360007700595,UNITY CENTER FOR URBAN TECHNOLOGIES,111 E 33RD ST,NEW YORK,NY,10016,2.25,2.12,1,1,3,1051.0,6.672268e+05
315,360008805179,BRONX HIGH SCHOOL FOR THE VISUAL ARTS,2040 ANTIN PL,BRONX,NY,10462,2.37,2.11,1,1,1,1270.0,1.069942e+05
316,360008305784,CITY COLLEGE ACADEMY OF THE ARTS,4600 BROADWAY,NEW YORK,NY,10040,2.80,2.87,NaN,NaN,NaN,1360.0,3.436245e+05
317,360015302032,MIDWOOD HIGH SCHOOL,2839 BEDFORD AVE,BROOKLYN,NY,11210,3.06,3.05,3,3,3,1561.0,4.525638e+05

In [174]:
'''This function finds the correlation and the significance of that correlation between 
the school quality (measured by average SAT score) and housing prices. The significance value (p-value) is used 
to see if there is enough evidence to reject the null hypothesis: There is no correlation between housing prices and quality of local high schools. '''
def findCorr():
    data = getFinalData()
    data = data[['Average 2014 Prices','Average SAT Score' ]].dropna()
    housingPrices = data['Average 2014 Prices']
    sat = data['Average SAT Score']
    corr, p = pearsonr(sat, housingPrices)
    if p < 0.05: 
        print("There is enough evidence to reject the null hypothesis: There is no correlation between housing prices and quality of local high schools.")
    else: 
        print("There is not enough evidence to reject the null hypothesis: There is no correlation between housing prices and quality of local high school.")
    data.plot(x='Average SAT Score', y='Average 2014 Prices', style='o')
    return corr, p
findCorr()

SyntaxError: invalid syntax (<ipython-input-174-0490181bdd48>, line 14)